--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_login_change_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_login_change_keys (
    id bigint NOT NULL,
    key text NOT NULL,
    login text NOT NULL,
    deadline timestamp with time zone NOT NULL
);


--
-- Name: account_password_reset_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_password_reset_keys (
    id bigint NOT NULL,
    key text NOT NULL,
    deadline timestamp with time zone NOT NULL,
    email_last_sent timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: account_remember_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_remember_keys (
    id bigint NOT NULL,
    key text NOT NULL,
    deadline timestamp with time zone NOT NULL
);


--
-- Name: account_verification_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_verification_keys (
    id bigint NOT NULL,
    key text NOT NULL,
    requested_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email_last_sent timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    email public.citext NOT NULL,
    status integer DEFAULT 1 NOT NULL,
    password_hash text,
    tenant_id bigint,
    super_admin boolean DEFAULT false NOT NULL,
    role text DEFAULT 'admin'::text NOT NULL,
    CONSTRAINT accounts_role_valid CHECK ((role = ANY (ARRAY['admin'::text, 'plumber'::text]))),
    CONSTRAINT valid_email CHECK ((email OPERATOR(public.~) '^[^,;@ \r\n]+@[^,@; \r\n]+\.[^,@; \r\n]+$'::public.citext))
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    id bigint NOT NULL,
    name text NOT NULL,
    slug public.citext NOT NULL,
    email public.citext,
    phone text,
    street text,
    city text,
    state text,
    postal_code text,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: impersonation_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.impersonation_events (
    id bigint NOT NULL,
    impersonation_session_id bigint NOT NULL,
    request_method text NOT NULL,
    path text NOT NULL,
    controller_action text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: impersonation_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.impersonation_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.impersonation_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: impersonation_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.impersonation_sessions (
    id bigint NOT NULL,
    impersonator_account_id bigint NOT NULL,
    impersonated_account_id bigint NOT NULL,
    tenant_id bigint,
    ip_address text,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ended_at timestamp with time zone
);


--
-- Name: impersonation_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.impersonation_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.impersonation_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plumbers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plumbers (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    account_id bigint,
    name text NOT NULL,
    company_name text,
    email public.citext,
    phone text,
    cert_number text NOT NULL,
    cert_status text DEFAULT 'pending'::text NOT NULL,
    cert_date date,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT plumbers_cert_status_valid CHECK ((cert_status = ANY (ARRAY['pending'::text, 'verified'::text, 'expired'::text, 'revoked'::text])))
);


--
-- Name: plumbers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plumbers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plumbers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: account_login_change_keys account_login_change_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_login_change_keys
    ADD CONSTRAINT account_login_change_keys_pkey PRIMARY KEY (id);


--
-- Name: account_password_reset_keys account_password_reset_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_password_reset_keys
    ADD CONSTRAINT account_password_reset_keys_pkey PRIMARY KEY (id);


--
-- Name: account_remember_keys account_remember_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_remember_keys
    ADD CONSTRAINT account_remember_keys_pkey PRIMARY KEY (id);


--
-- Name: account_verification_keys account_verification_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_verification_keys
    ADD CONSTRAINT account_verification_keys_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: tenants companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: impersonation_events impersonation_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impersonation_events
    ADD CONSTRAINT impersonation_events_pkey PRIMARY KEY (id);


--
-- Name: impersonation_sessions impersonation_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impersonation_sessions
    ADD CONSTRAINT impersonation_sessions_pkey PRIMARY KEY (id);


--
-- Name: plumbers plumbers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plumbers
    ADD CONSTRAINT plumbers_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: accounts_company_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_company_id_index ON public.accounts USING btree (tenant_id);


--
-- Name: accounts_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX accounts_email_index ON public.accounts USING btree (email) WHERE (status = ANY (ARRAY[1, 2]));


--
-- Name: companies_slug_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX companies_slug_index ON public.tenants USING btree (slug);


--
-- Name: impersonation_events_impersonation_session_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX impersonation_events_impersonation_session_id_index ON public.impersonation_events USING btree (impersonation_session_id);


--
-- Name: impersonation_sessions_impersonated_account_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX impersonation_sessions_impersonated_account_id_index ON public.impersonation_sessions USING btree (impersonated_account_id);


--
-- Name: impersonation_sessions_impersonator_account_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX impersonation_sessions_impersonator_account_id_index ON public.impersonation_sessions USING btree (impersonator_account_id);


--
-- Name: impersonation_sessions_tenant_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX impersonation_sessions_tenant_id_index ON public.impersonation_sessions USING btree (tenant_id);


--
-- Name: plumbers_account_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plumbers_account_id_index ON public.plumbers USING btree (account_id);


--
-- Name: plumbers_tenant_id_cert_number_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX plumbers_tenant_id_cert_number_index ON public.plumbers USING btree (tenant_id, cert_number);


--
-- Name: account_login_change_keys account_login_change_keys_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_login_change_keys
    ADD CONSTRAINT account_login_change_keys_id_fkey FOREIGN KEY (id) REFERENCES public.accounts(id);


--
-- Name: account_password_reset_keys account_password_reset_keys_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_password_reset_keys
    ADD CONSTRAINT account_password_reset_keys_id_fkey FOREIGN KEY (id) REFERENCES public.accounts(id);


--
-- Name: account_remember_keys account_remember_keys_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_remember_keys
    ADD CONSTRAINT account_remember_keys_id_fkey FOREIGN KEY (id) REFERENCES public.accounts(id);


--
-- Name: account_verification_keys account_verification_keys_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_verification_keys
    ADD CONSTRAINT account_verification_keys_id_fkey FOREIGN KEY (id) REFERENCES public.accounts(id);


--
-- Name: accounts accounts_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_company_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: impersonation_events impersonation_events_impersonation_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impersonation_events
    ADD CONSTRAINT impersonation_events_impersonation_session_id_fkey FOREIGN KEY (impersonation_session_id) REFERENCES public.impersonation_sessions(id);


--
-- Name: impersonation_sessions impersonation_sessions_impersonated_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impersonation_sessions
    ADD CONSTRAINT impersonation_sessions_impersonated_account_id_fkey FOREIGN KEY (impersonated_account_id) REFERENCES public.accounts(id);


--
-- Name: impersonation_sessions impersonation_sessions_impersonator_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impersonation_sessions
    ADD CONSTRAINT impersonation_sessions_impersonator_account_id_fkey FOREIGN KEY (impersonator_account_id) REFERENCES public.accounts(id);


--
-- Name: impersonation_sessions impersonation_sessions_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impersonation_sessions
    ADD CONSTRAINT impersonation_sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: plumbers plumbers_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plumbers
    ADD CONSTRAINT plumbers_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: plumbers plumbers_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plumbers
    ADD CONSTRAINT plumbers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;
INSERT INTO "schema_migrations" ("filename") VALUES ('20250513161713_create_rodauth.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260812222010_create_companies.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260813093655_add_super_admin_to_accounts.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260813171300_rename_companies_to_tenants.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260813171956_add_role_to_accounts.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260813172603_create_plumbers.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260814172904_create_impersonation_tables.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260815203000_use_timestamptz_for_impersonation_audit.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20260816021500_use_timestamptz_everywhere.rb');